[package]
name = "media-duplicate-eraser-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mde"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
thiserror = "2"
log = "0.4"
env_logger = "0.11"
